[package]
name = "rusty-particle-hub"
version = "0.1.0"
authors = ["jonathanzalger <misc+github@jzalger.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
